-- name: UpsertGames :exec
INSERT INTO games (
    tournament,
    team1_role1,
    team1_role2,
    team1_role3,
    team1_role4,
    team1_role5,
    team2_role1,
    team2_role2,
    team2_role3,
    team2_role4,
    team2_role5,
    team1_ban1,
    team1_ban2,
    team1_ban3,
    team1_ban4,
    team1_ban5,
    team1_pick1,
    team1_pick2,
    team1_pick3,
    team1_pick4,
    team1_pick5,
    team2_ban1,
    team2_ban2,
    team2_ban3,
    team2_ban4,
    team2_ban5,
    team2_pick1,
    team2_pick2,
    team2_pick3,
    team2_pick4,
    team2_pick5,
    team1,
    team2,
    winner,
    team1_picks_by_role_order,
    team2_picks_by_role_order,
    game_id,
    match_id,
    date_time_utc
)
SELECT
    unnest($1::text[]),
    unnest($2::text[]),
    unnest($3::text[]),
    unnest($4::text[]),
    unnest($5::text[]),
    unnest($6::text[]),
    unnest($7::text[]),
    unnest($8::text[]),
    unnest($9::text[]),
    unnest($10::text[]),
    unnest($11::text[]),
    unnest($12::text[]),
    unnest($13::text[]),
    unnest($14::text[]),
    unnest($15::text[]),
    unnest($16::text[]),
    unnest($17::text[]),
    unnest($18::text[]),
    unnest($19::text[]),
    unnest($20::text[]),
    unnest($21::text[]),
    unnest($22::text[]),
    unnest($23::text[]),
    unnest($24::text[]),
    unnest($25::text[]),
    unnest($26::text[]),
    unnest($27::text[]),
    unnest($28::text[]),
    unnest($29::text[]),
    unnest($30::text[]),
    unnest($31::text[]),
    unnest($32::text[]),
    unnest($33::text[]),
    unnest($34::text[]),
    unnest($35::text[]),
    unnest($36::text[]),
    unnest($37::text[]),
    unnest($38::text[]),
    unnest($39::timestamptz[])
ON CONFLICT (game_id) DO UPDATE SET
    tournament                = EXCLUDED.tournament,
    team1_role1               = EXCLUDED.team1_role1,
    team1_role2               = EXCLUDED.team1_role2,
    team1_role3               = EXCLUDED.team1_role3,
    team1_role4               = EXCLUDED.team1_role4,
    team1_role5               = EXCLUDED.team1_role5,
    team2_role1               = EXCLUDED.team2_role1,
    team2_role2               = EXCLUDED.team2_role2,
    team2_role3               = EXCLUDED.team2_role3,
    team2_role4               = EXCLUDED.team2_role4,
    team2_role5               = EXCLUDED.team2_role5,
    team1_ban1                = EXCLUDED.team1_ban1,
    team1_ban2                = EXCLUDED.team1_ban2,
    team1_ban3                = EXCLUDED.team1_ban3,
    team1_ban4                = EXCLUDED.team1_ban4,
    team1_ban5                = EXCLUDED.team1_ban5,
    team1_pick1               = EXCLUDED.team1_pick1,
    team1_pick2               = EXCLUDED.team1_pick2,
    team1_pick3               = EXCLUDED.team1_pick3,
    team1_pick4               = EXCLUDED.team1_pick4,
    team1_pick5               = EXCLUDED.team1_pick5,
    team2_ban1                = EXCLUDED.team2_ban1,
    team2_ban2                = EXCLUDED.team2_ban2,
    team2_ban3                = EXCLUDED.team2_ban3,
    team2_ban4                = EXCLUDED.team2_ban4,
    team2_ban5                = EXCLUDED.team2_ban5,
    team2_pick1               = EXCLUDED.team2_pick1,
    team2_pick2               = EXCLUDED.team2_pick2,
    team2_pick3               = EXCLUDED.team2_pick3,
    team2_pick4               = EXCLUDED.team2_pick4,
    team2_pick5               = EXCLUDED.team2_pick5,
    team1                     = EXCLUDED.team1,
    team2                     = EXCLUDED.team2,
    winner                    = EXCLUDED.winner,
    team1_picks_by_role_order = EXCLUDED.team1_picks_by_role_order,
    team2_picks_by_role_order = EXCLUDED.team2_picks_by_role_order,
    match_id                  = EXCLUDED.match_id,
    date_time_utc             = EXCLUDED.date_time_utc;