// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: champions.sql

package db

import (
	"context"
)

const addChampions = `-- name: AddChampions :one

INSERT INTO champions (champ_name)
VALUES ($1)
ON CONFLICT (champ_name) DO UPDATE SET
    champ_name = EXCLUDED.champ_name
RETURNING id, champ_name
`

func (q *Queries) AddChampions(ctx context.Context, champName string) (Champion, error) {
	row := q.db.QueryRowContext(ctx, addChampions, champName)
	var i Champion
	err := row.Scan(&i.ID, &i.ChampName)
	return i, err
}
