// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: champions_data.sql

package db

import (
	"context"
)

const clearChampionStats = `-- name: ClearChampionStats :exec
DELETE FROM champions_data
`

func (q *Queries) ClearChampionStats(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, clearChampionStats)
	return err
}

const updateChampionStats = `-- name: UpdateChampionStats :exec

WITH picks AS (
    SELECT p.champ, p.role (
        (gt.side = 1 AND g.winner = '1') OR
        (gt.side = 2 AND g.winner = '2')
    ) AS won
    FROM game_teams gt
    JOIN games g ON g.ID = gt.game_id
    CROSS JOIN LATERAL unnest(gt.picks) WITH ORDINALITY AS p(champ, idx)
    JOIN LATERAL unnest(gt.roles) WITH ORDINALITY AS r(role, idx) ON r.idx = p.idx 
),
agg AS (
    SELECT champ,
    COUNT(*) AS times_picked,
    COUNT(*) FILTER (WHERE role = 'Top') AS picked_top,
    COUNT(*) FILTER (WHERE role = 'Mid') AS picked_mid,
    COUNT(*) FILTER (WHERE role = 'Bot') AS picked_adc,
    COUNT(*) FILTER (WHERE role = 'Support') AS picked_sup,
    COUNT(*) FILTER (WHERE role = 'Jungle') AS picked_jungle,
    COUNT(*) FILTER (WHERE role = 'Top' AND won) AS wins_top,
    COUNT(*) FILTER (WHERE role = 'Mid' AND won) AS wins_mid,
    COUNT(*) FILTER (WHERE role = 'Bot' AND won) AS wins_adc,
    COUNT(*) FILTER (WHERE role = 'Support' AND won) AS wins_sup,
    COUNT(*) FILTER (WHERE role = 'Jungle' AND won) AS wins_jg,
    COUNT(*) FILTER (WHERE role = 'Top' AND NOT won) AS losses_top,
    COUNT(*) FILTER (WHERE role = 'Mid' AND NOT won) AS losses_mid,
    COUNT(*) FILTER (WHERE role = 'Bot' AND NOT won) AS losses_adc,
    COUNT(*) FILTER (WHERE role = 'Support' AND NOT won) AS losses_sup,
    COUNT(*) FILTER (WHERE role = 'Jungle' AND NOT won) AS losses_jg
    FROM picks
    GROUP BY champ
)INSERT INTO champions_data(
    champ_id,
    times_picked,
    picked_top,
    picked_mid,
    picked_adc,
    picked_sup,
    picked_jungle,
    wins_top,
    wins_mid,
    wins_jg,
    wins_adc,
    wins_sup,
    losses_top,
    losses_jg,
    losses_mid,
    losses_adc,
    losses_sup
)SELECT
    c.id,
    a.times_picked,
    a.picked_top,
    a.picked_mid,
    a.picked_adc,
    a.picked_sup,
    a.picked_jungle,
    a.wins_top,
    a.wins_mid,
    a.wins_jg,
    a.wins_adc,
    a.wins_sup,
    a.losses_top,
    a.losses_jg,
    a.losses_mid,
    a.losses_adc,
    a.losses_sup
FROM agg a
JOIN champions c ON c.champ_name = a.champ
`

func (q *Queries) UpdateChampionStats(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, updateChampionStats)
	return err
}
