// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: champions.sql

package db

import (
	"context"
	"database/sql"
)

const addChampions = `-- name: AddChampions :one

INSERT INTO champions (champ_name)
VALUES ($1)
RETURNING id, champ_name, times_picked, picked_top, picked_jungle, picked_mid, picked_adc, picked_sup, wins_top, losses_top, wins_jg, losses_jg, wins_mid, losses_mid, wins_adc, losses_adc, wins_sup, losses_sup, ingame_role
`

func (q *Queries) AddChampions(ctx context.Context, champName string) (Champion, error) {
	row := q.db.QueryRowContext(ctx, addChampions, champName)
	var i Champion
	err := row.Scan(
		&i.ID,
		&i.ChampName,
		&i.TimesPicked,
		&i.PickedTop,
		&i.PickedJungle,
		&i.PickedMid,
		&i.PickedAdc,
		&i.PickedSup,
		&i.WinsTop,
		&i.LossesTop,
		&i.WinsJg,
		&i.LossesJg,
		&i.WinsMid,
		&i.LossesMid,
		&i.WinsAdc,
		&i.LossesAdc,
		&i.WinsSup,
		&i.LossesSup,
		&i.IngameRole,
	)
	return i, err
}

const changeRoles = `-- name: ChangeRoles :one
UPDATE champions
SET ingame_role = $1
WHERE champ_name = $2
RETURNING id, champ_name, times_picked, picked_top, picked_jungle, picked_mid, picked_adc, picked_sup, wins_top, losses_top, wins_jg, losses_jg, wins_mid, losses_mid, wins_adc, losses_adc, wins_sup, losses_sup, ingame_role
`

type ChangeRolesParams struct {
	IngameRole sql.NullString
	ChampName  string
}

func (q *Queries) ChangeRoles(ctx context.Context, arg ChangeRolesParams) (Champion, error) {
	row := q.db.QueryRowContext(ctx, changeRoles, arg.IngameRole, arg.ChampName)
	var i Champion
	err := row.Scan(
		&i.ID,
		&i.ChampName,
		&i.TimesPicked,
		&i.PickedTop,
		&i.PickedJungle,
		&i.PickedMid,
		&i.PickedAdc,
		&i.PickedSup,
		&i.WinsTop,
		&i.LossesTop,
		&i.WinsJg,
		&i.LossesJg,
		&i.WinsMid,
		&i.LossesMid,
		&i.WinsAdc,
		&i.LossesAdc,
		&i.WinsSup,
		&i.LossesSup,
		&i.IngameRole,
	)
	return i, err
}

const updateStatus = `-- name: UpdateStatus :one
UPDATE champions
SET
    times_picked=$1,
    picked_top=$2,
    picked_jungle=$3,
    picked_mid=$4,
    picked_adc=$5,
    picked_sup=$6,
    wins_top=$7,
    losses_top=$8,
    wins_jg=$9,
    losses_jg=$10,
    wins_mid=$11,
    losses_mid=$12,
    wins_adc=$13,
    losses_adc=$14,
    wins_sup=$15,
    losses_sup=$16
WHERE champ_name = $17
RETURNING id, champ_name, times_picked, picked_top, picked_jungle, picked_mid, picked_adc, picked_sup, wins_top, losses_top, wins_jg, losses_jg, wins_mid, losses_mid, wins_adc, losses_adc, wins_sup, losses_sup, ingame_role
`

type UpdateStatusParams struct {
	TimesPicked  sql.NullInt32
	PickedTop    sql.NullInt32
	PickedJungle sql.NullInt32
	PickedMid    sql.NullInt32
	PickedAdc    sql.NullInt32
	PickedSup    sql.NullInt32
	WinsTop      sql.NullInt32
	LossesTop    sql.NullInt32
	WinsJg       sql.NullInt32
	LossesJg     sql.NullInt32
	WinsMid      sql.NullInt32
	LossesMid    sql.NullInt32
	WinsAdc      sql.NullInt32
	LossesAdc    sql.NullInt32
	WinsSup      sql.NullInt32
	LossesSup    sql.NullInt32
	ChampName    string
}

func (q *Queries) UpdateStatus(ctx context.Context, arg UpdateStatusParams) (Champion, error) {
	row := q.db.QueryRowContext(ctx, updateStatus,
		arg.TimesPicked,
		arg.PickedTop,
		arg.PickedJungle,
		arg.PickedMid,
		arg.PickedAdc,
		arg.PickedSup,
		arg.WinsTop,
		arg.LossesTop,
		arg.WinsJg,
		arg.LossesJg,
		arg.WinsMid,
		arg.LossesMid,
		arg.WinsAdc,
		arg.LossesAdc,
		arg.WinsSup,
		arg.LossesSup,
		arg.ChampName,
	)
	var i Champion
	err := row.Scan(
		&i.ID,
		&i.ChampName,
		&i.TimesPicked,
		&i.PickedTop,
		&i.PickedJungle,
		&i.PickedMid,
		&i.PickedAdc,
		&i.PickedSup,
		&i.WinsTop,
		&i.LossesTop,
		&i.WinsJg,
		&i.LossesJg,
		&i.WinsMid,
		&i.LossesMid,
		&i.WinsAdc,
		&i.LossesAdc,
		&i.WinsSup,
		&i.LossesSup,
		&i.IngameRole,
	)
	return i, err
}
