// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: champions.sql

package db

import (
	"context"
	"database/sql"
)

const addChampions = `-- name: AddChampions :one

INSERT INTO champions (champ_name)
VALUES ($1)
ON CONFLICT (champ_name) DO UPDATE SET
    champ_name = EXCLUDED.champ_name
RETURNING id, champ_name, times_picked, picked_top, picked_jungle, picked_mid, picked_adc, picked_sup, wins_top, losses_top, wins_jg, losses_jg, wins_mid, losses_mid, wins_adc, losses_adc, wins_sup, losses_sup, ingame_role
`

func (q *Queries) AddChampions(ctx context.Context, champName string) (Champion, error) {
	row := q.db.QueryRowContext(ctx, addChampions, champName)
	var i Champion
	err := row.Scan(
		&i.ID,
		&i.ChampName,
		&i.TimesPicked,
		&i.PickedTop,
		&i.PickedJungle,
		&i.PickedMid,
		&i.PickedAdc,
		&i.PickedSup,
		&i.WinsTop,
		&i.LossesTop,
		&i.WinsJg,
		&i.LossesJg,
		&i.WinsMid,
		&i.LossesMid,
		&i.WinsAdc,
		&i.LossesAdc,
		&i.WinsSup,
		&i.LossesSup,
		&i.IngameRole,
	)
	return i, err
}

const changeRoles = `-- name: ChangeRoles :one
UPDATE champions
SET ingame_role = $1
WHERE champ_name = $2
RETURNING id, champ_name, times_picked, picked_top, picked_jungle, picked_mid, picked_adc, picked_sup, wins_top, losses_top, wins_jg, losses_jg, wins_mid, losses_mid, wins_adc, losses_adc, wins_sup, losses_sup, ingame_role
`

type ChangeRolesParams struct {
	IngameRole sql.NullString
	ChampName  string
}

func (q *Queries) ChangeRoles(ctx context.Context, arg ChangeRolesParams) (Champion, error) {
	row := q.db.QueryRowContext(ctx, changeRoles, arg.IngameRole, arg.ChampName)
	var i Champion
	err := row.Scan(
		&i.ID,
		&i.ChampName,
		&i.TimesPicked,
		&i.PickedTop,
		&i.PickedJungle,
		&i.PickedMid,
		&i.PickedAdc,
		&i.PickedSup,
		&i.WinsTop,
		&i.LossesTop,
		&i.WinsJg,
		&i.LossesJg,
		&i.WinsMid,
		&i.LossesMid,
		&i.WinsAdc,
		&i.LossesAdc,
		&i.WinsSup,
		&i.LossesSup,
		&i.IngameRole,
	)
	return i, err
}

const updateChampionStats = `-- name: UpdateChampionStats :exec

WITH reset AS (
    UPDATE champions SET 
  times_picked = 0, picked_top = 0, picked_jungle = 0,
  picked_mid = 0, picked_adc = 0, picked_sup = 0,
  wins_top = 0, losses_top = 0, wins_jg = 0, losses_jg = 0,
  wins_mid = 0, losses_mid = 0, wins_adc = 0, losses_adc = 0,
  wins_sup = 0, losses_sup = 0
),
picks AS (
    SELECT champ, role, won FROM (
        SELECT team1_pick1 AS champ, team1_role1 AS role, (winner='1') AS won FROM games
        UNION ALL
        SELECT team1_pick2 AS champ, team1_role2 AS role, (winner='1') AS won FROM games
        UNION ALL
        SELECT team1_pick3 AS champ, team1_role3 AS role, (winner='1') AS won FROM games
        UNION ALL
        SELECT team1_pick4 AS champ, team1_role4 AS role, (winner='1') AS won FROM games
        UNION ALL
        SELECT team1_pick5 AS champ, team1_role5 AS role, (winner='1') AS won FROM games
        UNION ALL
        SELECT team2_pick1 AS champ, team2_role1 AS role, (winner='2') AS won FROM games
        UNION ALL
        SELECT team2_pick2 AS champ, team2_role2 AS role, (winner='2') AS won FROM games
        UNION ALL
        SELECT team2_pick3 AS champ, team2_role3 AS role, (winner='2') AS won FROM games
        UNION ALL
        SELECT team2_pick4 AS champ, team2_role4 AS role, (winner='2') AS won FROM games
        UNION ALL
        SELECT team2_pick5 AS champ, team2_role5 AS role, (winner='2') AS won FROM games
    ) sub), agg AS (
        SELECT
        champ,
        COUNT(*) AS times_picked,
        COUNT(*) FILTER (WHERE role = 'Top') AS picked_top,
        COUNT(*) FILTER (WHERE role = 'Jungle') AS picked_jungle,
        COUNT(*) FILTER (WHERE role = 'Mid') AS picked_mid,
        COUNT(*) FILTER (WHERE role = 'Bot') AS picked_adc,
        COUNT(*) FILTER (WHERE role = 'Support') AS picked_sup,
        COUNT(*) FILTER (WHERE role = 'Top' AND won) AS wins_top,
        COUNT(*) FILTER (WHERE role = 'Jungle' AND won) AS wins_jg,
        COUNT(*) FILTER (WHERE role = 'Mid' AND won) AS wins_mid,
        COUNT(*) FILTER (WHERE role = 'Bot' AND won) AS wins_adc,
        COUNT(*) FILTER (WHERE role = 'Support' AND won) AS wins_sup,
        COUNT(*) FILTER (WHERE role = 'Top' AND NOT won) AS losses_top,
        COUNT(*) FILTER (WHERE role = 'Jungle' AND NOT won) AS losses_jg,
        COUNT(*) FILTER (WHERE role = 'Mid' AND NOT won) AS losses_mid,
        COUNT(*) FILTER (WHERE role = 'Bot' AND NOT won) AS losses_adc,
        COUNT(*) FILTER (WHERE role = 'Support' AND NOT won) AS losses_sup
        FROM picks
        GROUP BY champ
    )
    UPDATE champions c 
    SET
        times_picked  = a.times_picked,
        picked_top    = a.picked_top,
        picked_jungle = a.picked_jungle,
        picked_mid    = a.picked_mid,
        picked_adc    = a.picked_adc,
        picked_sup    = a.picked_sup,
        wins_top      = a.wins_top,
        losses_top    = a.losses_top,
        wins_jg       = a.wins_jg,
        losses_jg     = a.losses_jg,
        wins_mid      = a.wins_mid,
        losses_mid    = a.losses_mid,
        wins_adc      = a.wins_adc,
        losses_adc    = a.losses_adc,
        wins_sup      = a.wins_sup,
        losses_sup    = a.losses_sup
    FROM agg a
    WHERE c.champ_name = a.champ
`

func (q *Queries) UpdateChampionStats(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, updateChampionStats)
	return err
}

const updateStatus = `-- name: UpdateStatus :one
UPDATE champions
SET
    times_picked=$1,
    picked_top=$2,
    picked_jungle=$3,
    picked_mid=$4,
    picked_adc=$5,
    picked_sup=$6,
    wins_top=$7,
    losses_top=$8,
    wins_jg=$9,
    losses_jg=$10,
    wins_mid=$11,
    losses_mid=$12,
    wins_adc=$13,
    losses_adc=$14,
    wins_sup=$15,
    losses_sup=$16
WHERE champ_name = $17
RETURNING id, champ_name, times_picked, picked_top, picked_jungle, picked_mid, picked_adc, picked_sup, wins_top, losses_top, wins_jg, losses_jg, wins_mid, losses_mid, wins_adc, losses_adc, wins_sup, losses_sup, ingame_role
`

type UpdateStatusParams struct {
	TimesPicked  sql.NullInt32
	PickedTop    sql.NullInt32
	PickedJungle sql.NullInt32
	PickedMid    sql.NullInt32
	PickedAdc    sql.NullInt32
	PickedSup    sql.NullInt32
	WinsTop      sql.NullInt32
	LossesTop    sql.NullInt32
	WinsJg       sql.NullInt32
	LossesJg     sql.NullInt32
	WinsMid      sql.NullInt32
	LossesMid    sql.NullInt32
	WinsAdc      sql.NullInt32
	LossesAdc    sql.NullInt32
	WinsSup      sql.NullInt32
	LossesSup    sql.NullInt32
	ChampName    string
}

func (q *Queries) UpdateStatus(ctx context.Context, arg UpdateStatusParams) (Champion, error) {
	row := q.db.QueryRowContext(ctx, updateStatus,
		arg.TimesPicked,
		arg.PickedTop,
		arg.PickedJungle,
		arg.PickedMid,
		arg.PickedAdc,
		arg.PickedSup,
		arg.WinsTop,
		arg.LossesTop,
		arg.WinsJg,
		arg.LossesJg,
		arg.WinsMid,
		arg.LossesMid,
		arg.WinsAdc,
		arg.LossesAdc,
		arg.WinsSup,
		arg.LossesSup,
		arg.ChampName,
	)
	var i Champion
	err := row.Scan(
		&i.ID,
		&i.ChampName,
		&i.TimesPicked,
		&i.PickedTop,
		&i.PickedJungle,
		&i.PickedMid,
		&i.PickedAdc,
		&i.PickedSup,
		&i.WinsTop,
		&i.LossesTop,
		&i.WinsJg,
		&i.LossesJg,
		&i.WinsMid,
		&i.LossesMid,
		&i.WinsAdc,
		&i.LossesAdc,
		&i.WinsSup,
		&i.LossesSup,
		&i.IngameRole,
	)
	return i, err
}
