// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"time"
)

type Champion struct {
	ID        int32
	ChampName string
}

type ChampionsDatum struct {
	ChampID      int32
	TimesPicked  sql.NullInt32
	PickedTop    sql.NullInt32
	PickedJungle sql.NullInt32
	PickedMid    sql.NullInt32
	PickedAdc    sql.NullInt32
	PickedSup    sql.NullInt32
	WinsTop      sql.NullInt32
	LossesTop    sql.NullInt32
	WinsJg       sql.NullInt32
	LossesJg     sql.NullInt32
	WinsMid      sql.NullInt32
	LossesMid    sql.NullInt32
	WinsAdc      sql.NullInt32
	LossesAdc    sql.NullInt32
	WinsSup      sql.NullInt32
	LossesSup    sql.NullInt32
}

type Game struct {
	ID          int32
	Patch       sql.NullString
	Tournament  string
	Team1       string
	Team2       string
	Winner      string
	GameID      string
	MatchID     string
	DateTimeUtc time.Time
}

type GameTeam struct {
	ID     int32
	GameID int32
	Side   int32
	Name   string
	Roles  []string
	Picks  []string
	Bans   []string
}

type UpdateLog struct {
	Region        string
	LastUpdatedAt time.Time
}
