// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"time"
)

type Champion struct {
	ID           int32
	ChampName    string
	TimesPicked  sql.NullInt32
	PickedTop    sql.NullInt32
	PickedJungle sql.NullInt32
	PickedMid    sql.NullInt32
	PickedAdc    sql.NullInt32
	PickedSup    sql.NullInt32
	WinsTop      sql.NullInt32
	LossesTop    sql.NullInt32
	WinsJg       sql.NullInt32
	LossesJg     sql.NullInt32
	WinsMid      sql.NullInt32
	LossesMid    sql.NullInt32
	WinsAdc      sql.NullInt32
	LossesAdc    sql.NullInt32
	WinsSup      sql.NullInt32
	LossesSup    sql.NullInt32
	IngameRole   sql.NullString
}

type Game struct {
	ID                    int32
	Tournament            string
	Team1Role1            string
	Team1Role2            string
	Team1Role3            string
	Team1Role4            string
	Team1Role5            string
	Team2Role1            string
	Team2Role2            string
	Team2Role3            string
	Team2Role4            string
	Team2Role5            string
	Team1Ban1             string
	Team1Ban2             string
	Team1Ban3             string
	Team1Ban4             string
	Team1Ban5             string
	Team1Pick1            string
	Team1Pick2            string
	Team1Pick3            string
	Team1Pick4            string
	Team1Pick5            string
	Team2Ban1             string
	Team2Ban2             string
	Team2Ban3             string
	Team2Ban4             string
	Team2Ban5             string
	Team2Pick1            string
	Team2Pick2            string
	Team2Pick3            string
	Team2Pick4            string
	Team2Pick5            string
	Team1                 string
	Team2                 string
	Winner                string
	Team1PicksByRoleOrder string
	Team2PicksByRoleOrder string
	GameID                string
	MatchID               string
	DateTimeUtc           time.Time
}

type UpdateLog struct {
	Region        string
	LastUpdatedAt time.Time
}
