// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: update_log.sql

package db

import (
	"context"
	"time"
)

const getUpdateRecord = `-- name: GetUpdateRecord :one
SELECT region, last_updated_at from update_log WHERE region = $1
`

func (q *Queries) GetUpdateRecord(ctx context.Context, region string) (UpdateLog, error) {
	row := q.db.QueryRowContext(ctx, getUpdateRecord, region)
	var i UpdateLog
	err := row.Scan(&i.Region, &i.LastUpdatedAt)
	return i, err
}

const upsertRecord = `-- name: UpsertRecord :exec

INSERT INTO update_log (
    region,
    last_updated_at
)VALUES(
    $1, $2
)
ON CONFLICT (region) DO UPDATE SET
    last_updated_at = EXCLUDED.last_updated_at
`

type UpsertRecordParams struct {
	Region        string
	LastUpdatedAt time.Time
}

func (q *Queries) UpsertRecord(ctx context.Context, arg UpsertRecordParams) error {
	_, err := q.db.ExecContext(ctx, upsertRecord, arg.Region, arg.LastUpdatedAt)
	return err
}
